baseURL: "https://yoursite.example.com/"
title: "Servidor Gerenciado"
theme : hugo-theme-stack

params:
  Subtitle: "Hugo is Absurdly Fast!"
  AuthorName: "Jon Doe"
  GitHubUser: "spf13"
  ListOfFoo:
    - "foo1"
    - "foo2"
  SidebarRecentLimit: 5

menu:
  main:
    - identifier: "lpi"
      name: "LPI"
      url: "/lpi/"
    
    - identifier:  "post"
      name: "POST"
      url: "/posts/" # user is taken to this url
      
    - identifier: "about" # different for all menu entries, useful especially when menu name coincides
      name: "About us" # shown on website/blog
      url: "/about/" # user is taken to this url when user clicks on menu item
      